[features]
seeds = false

[toolchain]
anchor_version = "0.24.2"

[programs.localnet]
solana_twitter = "3wkkNRHZCCMh1Ai1CoysC5vNEWS5e7ij2ztY19pwDuS3"

[programs.devnet]
solana_twitter = "3wkkNRHZCCMh1Ai1CoysC5vNEWS5e7ij2ztY19pwDuS3"

[programs.testnet]
solana_twitter = "3wkkNRHZCCMh1Ai1CoysC5vNEWS5e7ij2ztY19pwDuS3"

[programs.mainnet]
solana_twitter = "3wkkNRHZCCMh1Ai1CoysC5vNEWS5e7ij2ztY19pwDuS3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json && cp target/types/solana_tweeter.ts"

[workspace]
types = "app/src/idl/"
