[features]
seeds = false
[programs.localnet]
solana_twitter = "7GyjqgtmHTsLiS4Vr24GXck1uhJLBvkrxJQ5Ha4tw8at"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/thuyhoang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
