[package]
name = "solana_twitter"
version = "0.1.0"
description = "Optimized Solana Twitter Program"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "solana_twitter"

[dependencies]
solana-program = "1.18.26"

[profile.release]
# Optimize for size
opt-level = "z"  # Optimize for size
lto = true       # Link-time optimization
codegen-units = 1 # Single codegen unit for better optimization
panic = "abort"  # Smaller panic handler
strip = true     # Remove debug symbols

[profile.dev]
# Keep debug info for development
opt-level = 0
debug = true
